/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// PopowHeader struct for PopowHeader
type PopowHeader struct {
	Header BlockHeader `json:"header"`
	// Array of header interlinks
	Interlinks []string `json:"interlinks"`
}
