/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// GenerateCommitmentsRequestSecrets Optionally, external secrets used for signing
type GenerateCommitmentsRequestSecrets struct {
	// Sequence of secret exponents (DLOG secrets)
	Dlog []string `json:"dlog,omitempty"`
	// Sequence of secret Diffie-Hellman tuple exponents (DHT secrets)
	Dht []DhtSecret `json:"dht,omitempty"`
}
