/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// ProofOfUpcomingTransactions Proof that a block corresponding to given header without PoW contains some transactions
type ProofOfUpcomingTransactions struct {
	// Base16-encoded serialized header without Proof-of-Work
	MsgPreimage string `json:"msgPreimage"`
	// Merkle proofs of transactions included into blocks (not necessarily all the block transactions)
	TxProofs []MerkleProof `json:"txProofs"`
}
