/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// BlockHeaderWithoutPow struct for BlockHeaderWithoutPow
type BlockHeaderWithoutPow struct {
	// Base16-encoded 32 byte modifier id
	ID string `json:"id"`
	// Basic timestamp definition
	Timestamp int64 `json:"timestamp"`
	// Ergo blockchain protocol version
	Version int32 `json:"version"`
	// Base16-encoded 32 byte digest
	AdProofsRoot string `json:"adProofsRoot"`
	// Base16-encoded 33 byte digest - digest with extra byte with tree height
	StateRoot string `json:"stateRoot"`
	// Base16-encoded 32 byte digest
	TransactionsRoot string `json:"transactionsRoot"`
	NBits            int64  `json:"nBits"`
	// Base16-encoded 32 byte digest
	ExtensionHash string `json:"extensionHash"`
	Height        int32  `json:"height"`
	Difficulty    int32  `json:"difficulty"`
	// Base16-encoded 32 byte modifier id
	ParentID string `json:"parentID"`
	// Base16-encoded votes for a soft-fork and parameters
	Votes string `json:"votes"`
	// Size in bytes
	Size int32 `json:"size,omitempty"`
	// Base16-encoded 32 byte modifier id
	ExtensionID string `json:"extensionID,omitempty"`
	// Base16-encoded 32 byte modifier id
	TransactionsID string `json:"transactionsID,omitempty"`
	// Base16-encoded 32 byte modifier id
	AdProofsID string `json:"adProofsID,omitempty"`
}
