/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// PassphraseMatch struct for PassphraseMatch
type PassphraseMatch struct {
	// true if passphrase matches wallet, false otherwise
	Matched bool `json:"matched"`
}
