/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// WalletStatus Status of the node wallet
type WalletStatus struct {
	// true if wallet is initialized, false otherwise
	IsInitialized bool `json:"isInitialized"`
	// true if wallet is unlocked, false otherwise
	IsUnlocked bool `json:"isUnlocked"`
	// address to send change to. Empty when wallet is not initialized or locked. By default change address correponds to root key address, could be set via /wallet/updateChangeAddress method.
	ChangeAddress string `json:"changeAddress"`
	// last scanned height for the wallet (and external scans)
	WalletHeight int32 `json:"walletHeight"`
	// last wallet error caught
	Error string `json:"error"`
}
