/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// ErgoLikeTransaction struct for ErgoLikeTransaction
type ErgoLikeTransaction struct {
	// Base16-encoded 32 byte modifier id
	ID         string                     `json:"id"`
	Inputs     []ErgoTransactionInput     `json:"inputs"`
	DataInputs []ErgoTransactionDataInput `json:"dataInputs"`
	Outputs    []ErgoTransactionOutput    `json:"outputs"`
}
