/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// BlockTransactions struct for BlockTransactions
type BlockTransactions struct {
	// Base16-encoded 32 byte modifier id
	HeaderID string `json:"headerID"`
	// Ergo transaction objects
	Transactions []ErgoTransaction `json:"transactions"`
	// Size in bytes
	Size int32 `json:"size"`
}
