/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// TrackInfo struct for TrackInfo
type TrackInfo struct {
	InvalidModifierApproxSize int32 `json:"invalidModifierApproxSize"`
	// Currently requested modifiers
	Requested map[string]map[string]RequestedInfo `json:"requested"`
	// Received modifiers
	Received map[string]map[string]ConnectedPeer `json:"received"`
}
