/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// ExecuteScript struct for ExecuteScript
type ExecuteScript struct {
	// Sigma script to be executed
	Script string `json:"script"`
	// Environment for compiler
	NamedConstants *map[string]interface{} `json:"namedConstants"`
	Context        ErgoLikeContext         `json:"context"`
}
