/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// RequestsHolder Holds many transaction requests and transaction fee
type RequestsHolder struct {
	// Sequence of transaction requests
	Requests []interface{} `json:"requests"`
	// Transaction fee
	Fee int64 `json:"fee,omitempty"`
	// List of inputs to be used in serialized form
	InputsRaw []string `json:"inputsRaw,omitempty"`
	// List of data inputs to be used in serialized form
	DataInputsRaw []string `json:"dataInputsRaw,omitempty"`
}
