/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// PeersStatus struct for PeersStatus
type PeersStatus struct {
	LastIncomingMessage int64 `json:"lastIncomingMessage"`
	CurrentNetworkTime  int64 `json:"currentNetworkTime"`
}
