/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// InitWallet struct for InitWallet
type InitWallet struct {
	// Password to encrypt wallet file with
	Pass string `json:"pass"`
	// Optional pass to password-protect mnemonic seed
	MnemonicPass string `json:"mnemonicPass,omitempty"`
}
