/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// EmissionInfo Emission info for height
type EmissionInfo struct {
	MinerReward      int64 `json:"minerReward,omitempty"`
	TotalCoinsIssued int64 `json:"totalCoinsIssued,omitempty"`
	TotalRemainCoins int64 `json:"totalRemainCoins,omitempty"`
}
