/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// ScanRequest struct for ScanRequest
type ScanRequest struct {
	ScanName          string            `json:"scanName,omitempty"`
	RemoveOffchain    bool              `json:"removeOffchain,omitempty"`
	WalletInteraction string            `json:"walletInteraction,omitempty"`
	TrackingRule      ScanningPredicate `json:"trackingRule,omitempty"`
}
