/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// ScriptBytes struct for ScriptBytes
type ScriptBytes struct {
	// Base16-encoded bytes
	Bytes string `json:"bytes"`
}
