/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// BurnTokensRequest Request for burning tokens in wallet
type BurnTokensRequest struct {
	// Assets list to burn in the transaction
	AssetsToBurn []Asset `json:"assetsToBurn"`
}
