/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// BoxesRequestHolder Holds request for wallet boxes
type BoxesRequestHolder struct {
	// Target assets
	TargetAssets [][]interface{} `json:"targetAssets"`
	// Target balance
	TargetBalance int64 `json:"targetBalance"`
}
