/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// RequestedInfo struct for RequestedInfo
type RequestedInfo struct {
	Address string `json:"address,omitempty"`
	Version string `json:"version,omitempty"`
	// How many times we checked for modifier delivery status
	Checks int32 `json:"checks"`
}
