/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// PeerMode struct for PeerMode
type PeerMode struct {
	State                 string `json:"state"`
	VerifyingTransactions bool   `json:"verifyingTransactions"`
	FullBlocksSuffix      int32  `json:"fullBlocksSuffix"`
}
