/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// RewardPubKey struct for RewardPubKey
type RewardPubKey struct {
	RewardPubkey string `json:"rewardPubkey"`
}
