/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// SigmaBoolean Algebraic data type of sigma proposition expressions
type SigmaBoolean struct {
	// Sigma opCode
	Op int32 `json:"op"`
	// Base16-encoded bytes
	H string `json:"h,omitempty"`
	// Base16-encoded bytes
	G string `json:"g,omitempty"`
	// Base16-encoded bytes
	U string `json:"u,omitempty"`
	// Base16-encoded bytes
	V         string `json:"v,omitempty"`
	Condition bool   `json:"condition,omitempty"`
}
