/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// ConnectedPeer struct for ConnectedPeer
type ConnectedPeer struct {
	Address string `json:"address"`
	Version string `json:"version,omitempty"`
	// Basic timestamp definition
	LastMessage int64 `json:"lastMessage,omitempty"`
}
