/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// WorkMessage Block candidate related data for external miner to perform work
type WorkMessage struct {
	// Base16-encoded block header bytes without PoW solution
	Msg string `json:"msg"`
	// Work target value
	B int32 `json:"b"`
	// Base16-encoded miner public key
	Pk    string                      `json:"pk"`
	Proof ProofOfUpcomingTransactions `json:"proof,omitempty"`
}
