/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

import "math/big"

// PowSolutions An object containing all components of pow solution
type PowSolutions struct {
	// Base16-encoded public key
	Pk string  `json:"pk"`
	W  string  `json:"w"`
	N  string  `json:"n"`
	D  big.Int `json:"d"`
}
