/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// Asset Token detail in the transaction
type Asset struct {
	// Base16-encoded 32 byte digest
	TokenID string `json:"tokenID"`
	// Amount of the token
	Amount int64 `json:"amount"`
}
