/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// ScanIDsBox Ergo box with associated scans (their respective identifiers)
type ScanIDsBox struct {
	ScanIDs []int32               `json:"scanIDs"`
	Box     ErgoTransactionOutput `json:"box"`
}
