/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// MerkleProof Merkle proof for a leaf, which is an array of bytes (e.g. a transaction identifier)
type MerkleProof struct {
	// Base16-encoded Merkle tree leaf bytes
	Leaf   string          `json:"leaf"`
	Levels [][]interface{} `json:"levels"`
}
