/*
 * Ergo Node API
 *
 * API docs for Ergo Node. Models are shared between all Ergo products
 *
 * API version: 4.0.23
 * Contact: ergoplatform@protonmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ergo_rest

// SigmaHeader Block header format used for sigma ErgoLikeContext
type SigmaHeader struct {
	// Base16-encoded 32 byte modifier id
	ID string `json:"id,omitempty"`
	// Basic timestamp definition
	Timestamp int64 `json:"timestamp"`
	// Ergo blockchain protocol version
	Version int32 `json:"version"`
	// Base16-encoded 32 byte digest
	AdProofsRoot string `json:"adProofsRoot"`
	// Base16-encoded 32 byte modifier id
	AdProofsID string      `json:"adProofsID,omitempty"`
	StateRoot  AvlTreeData `json:"stateRoot"`
	// Base16-encoded 32 byte digest
	TransactionsRoot string `json:"transactionsRoot"`
	// Base16-encoded 32 byte modifier id
	TransactionsID string `json:"transactionsID,omitempty"`
	NBits          int64  `json:"nBits"`
	// Base16-encoded 32 byte digest
	ExtensionHash string `json:"extensionHash"`
	// Base16-encoded 32 byte digest
	ExtensionRoot string `json:"extensionRoot,omitempty"`
	// Base16-encoded 32 byte modifier id
	ExtensionID string `json:"extensionID,omitempty"`
	Height      int32  `json:"height"`
	Size        int32  `json:"size,omitempty"`
	// Base16-encoded 32 byte modifier id
	ParentID     string       `json:"parentID"`
	PowSolutions PowSolutions `json:"powSolutions,omitempty"`
	// Base16-encoded votes for a soft-fork and parameters
	Votes        string `json:"votes"`
	MinerPk      string `json:"minerPk,omitempty"`
	PowOnetimePk string `json:"powOnetimePk,omitempty"`
	// Base16-encoded 32 byte digest
	PowNonce string `json:"powNonce,omitempty"`
	// sigma.BigInt
	PowDistance float32 `json:"powDistance,omitempty"`
}
